- hosts: dbserver
  become: yes
  vars:
    mysql_root_password: 'rootpassword'
    phpmyadmin_user: 'phpmyadmin_user'
    phpmyadmin_password: 'phpmyadmin_password'
    ansible_remote_tmp: /dev/shm/.ansible/tmp
    ansible_ssh_extra_args: "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"  # Disable strict host key checking
  tasks:
    - name: Remove old host key from known_hosts
      command: ssh-keygen -f /home/debian/.ssh/known_hosts -R "{{ ansible_host }}" # Change the path to the known_hosts file 
      delegate_to: localhost
      when: ansible_host is defined

    - name: Update APT package index
      apt:
        update_cache: yes

    - name: Clean up APT cache
      command: apt-get clean

    - name: Fix interrupted dpkg
      shell: dpkg --configure -a

    - name: Purge broken MySQL installation
      apt:
        name: mysql-server
        state: absent

    - name: Set MySQL root password before installation
      debconf:
        name: mysql-server
        question: mysql-server/root_password
        value: "{{ mysql_root_password }}"
        vtype: password

    - name: Confirm MySQL root password before installation
      debconf:
        name: mysql-server
        question: mysql-server/root_password_again
        value: "{{ mysql_root_password }}"
        vtype: password

    - name: Install MySQL server
      apt:
        name: mysql-server
        state: present

    - name: Create MySQL user for phpMyAdmin
      shell: |
        mysql -u root -p{{ mysql_root_password }} -e "\
        CREATE USER IF NOT EXISTS '{{ phpmyadmin_user }}'@'localhost' IDENTIFIED BY '{{ phpmyadmin_password }}'; \
        GRANT ALL PRIVILEGES ON *.* TO '{{ phpmyadmin_user }}'@'localhost' WITH GRANT OPTION; \
        FLUSH PRIVILEGES;"

    - name: Ensure MySQL is running
      service:
        name: mysql
        state: started
        enabled: yes

    - name: Install phpMyAdmin dependencies
      apt:
        name: '{{ item }}'
        state: present
      loop:
        - php
        - php-mbstring
        - php-zip
        - php-gd
        - php-json
        - php-curl

    - name: Set debconf selections for phpMyAdmin installation
      debconf:
        name: phpmyadmin
        question: "{{ item.question }}"
        value: "{{ item.value }}"
        vtype: "{{ item.vtype }}"
      loop:
        - { question: 'phpmyadmin/dbconfig-install', value: 'true', vtype: 'boolean' }
        - { question: 'phpmyadmin/app-password-confirm', value: '', vtype: 'password' }
        - { question: 'phpmyadmin/mysql/admin-pass', value: '{{ mysql_root_password }}', vtype: 'password' }
        - { question: 'phpmyadmin/mysql/app-pass', value: '{{ phpmyadmin_password }}', vtype: 'password' }
        - { question: 'phpmyadmin/reconfigure-webserver', value: 'apache2', vtype: 'string' }

    - name: Install phpMyAdmin
      apt:
        name: phpmyadmin
        state: present

    - name: Ensure Apache is installed
      apt:
        name: apache2
        state: present

    - name: Ensure Apache is running
      service:
        name: apache2
        state: started
        enabled: yes
