- hosts: dbserver
  become: yes
  vars:
    mysql_root_password: 'rootpassword'
    phpmyadmin_user: 'phpmyadmin_user'
    phpmyadmin_password: 'phpmyadmin_password'
    ansible_remote_tmp: /dev/shm/.ansible/tmp
  tasks:
    - name: Remove Snap packages and unmount /snap
      shell: |
        snap remove lxd core20 snapd || true
        rm -rf /var/lib/snapd
        umount /snap || true
      ignore_errors: yes

    - name: Update APT package index
      apt:
        update_cache: yes
      ignore_errors: yes

    - name: Clean up APT cache
      command: apt-get clean
      ignore_errors: yes

    - name: Fix interrupted dpkg
      shell: dpkg --configure -a
      ignore_errors: yes

    - name: Purge broken MySQL installation
      apt:
        name: mysql-server
        state: absent
      ignore_errors: yes

    - name: Set MySQL root password before installation
      debconf:
        name: mysql-server
        question: mysql-server/root_password
        value: "{{ mysql_root_password }}"
        vtype: password

    - name: Confirm MySQL root password before installation
      debconf:
        name: mysql-server
        question: mysql-server/root_password_again
        value: "{{ mysql_root_password }}"
        vtype: password

    - name: Reinstall MySQL server
      apt:
        name: mysql-server
        state: present
      ignore_errors: yes

    - name: Create MySQL user for phpMyAdmin
      shell: |
        mysql -u root -p{{ mysql_root_password }} -e "\
        CREATE USER IF NOT EXISTS '{{ phpmyadmin_user }}'@'localhost' IDENTIFIED BY '{{ phpmyadmin_password }}'; \
        GRANT ALL PRIVILEGES ON *.* TO '{{ phpmyadmin_user }}'@'localhost' WITH GRANT OPTION; \
        FLUSH PRIVILEGES;"
      ignore_errors: yes

    - name: Disable AppArmor (if enabled)
      shell: |
        systemctl stop apparmor
        systemctl disable apparmor
      ignore_errors: yes

    - name: Ensure MySQL data directory permissions are correct
      file:
        path: /var/lib/mysql
        state: directory
        owner: mysql
        group: mysql
        mode: '0755'
      ignore_errors: yes

    - name: Reconfigure MySQL
      shell: dpkg-reconfigure mysql-server
      ignore_errors: yes

    - name: Ensure MySQL is running
      service:
        name: mysql
        state: started
        enabled: yes
      ignore_errors: yes

    - name: Install phpMyAdmin dependencies
      apt:
        name: '{{ item }}'
        state: present
      loop:
        - php
        - php-mbstring
        - php-zip
        - php-gd
        - php-json
        - php-curl
      ignore_errors: yes

    - name: Set debconf selections for phpMyAdmin installation
      debconf:
        name: phpmyadmin
        question: "{{ item.question }}"
        value: "{{ item.value }}"
        vtype: "{{ item.vtype }}"
      loop:
        - { question: 'phpmyadmin/dbconfig-install', value: 'true', vtype: 'boolean' }
        - { question: 'phpmyadmin/app-password-confirm', value: '', vtype: 'password' }
        - { question: 'phpmyadmin/mysql/admin-pass', value: '{{ mysql_root_password }}', vtype: 'password' }
        - { question: 'phpmyadmin/mysql/app-pass', value: '{{ phpmyadmin_password }}', vtype: 'password' }
        - { question: 'phpmyadmin/reconfigure-webserver', value: 'apache2', vtype: 'string' }

    - name: Install phpMyAdmin
      apt:
        name: phpmyadmin
        state: present
      ignore_errors: yes

    - name: Ensure Apache is installed
      apt:
        name: apache2
        state: present
      ignore_errors: yes

    - name: Ensure Apache is running
      service:
        name: apache2
        state: started
        enabled: yes
      ignore_errors: yes

    - name: Check MySQL service status
      shell: systemctl status mysql.service
      register: mysql_status
      ignore_errors: yes
    - debug:
        var: mysql_status.stdout_lines

    - name: Check journalctl for MySQL errors
      shell: journalctl -xe | tail -n 50
      register: mysql_journalctl
      ignore_errors: yes
    - debug:
        var: mysql_journalctl.stdout_lines