---
- hosts: local
  connection: local
  gather_facts: false
  tasks:
    - name: Install necessary packages
      package:
        name:
          - libvirt-clients
          - libvirt-daemon-system
          - qemu-kvm
          - genisoimage
        state: present

    - name: Download Ubuntu Cloud Image
      get_url:
        url: https://cloud-images.ubuntu.com/focal/current/focal-server-cloudimg-amd64.img
        dest: /var/lib/libvirt/images/focal-server-cloudimg-amd64.img
        mode: '0755'
      args:
        creates: /var/lib/libvirt/images/focal-server-cloudimg-amd64.img

    - name: Create VM disk for webserver
      command: >
        qemu-img create -f qcow2 -b /var/lib/libvirt/images/focal-server-cloudimg-amd64.img
        /var/lib/libvirt/images/webserver.qcow2 10G
      args:
        creates: /var/lib/libvirt/images/webserver.qcow2

    - name: Create VM disk for dbserver
      command: >
        qemu-img create -f qcow2 -b /var/lib/libvirt/images/focal-server-cloudimg-amd64.img
        /var/lib/libvirt/images/dbserver.qcow2 10G
      args:
        creates: /var/lib/libvirt/images/dbserver.qcow2

    - name: Create cloud-init user data for webserver
      copy:
        dest: /var/lib/libvirt/images/webserver-user-data
        content: |
          #cloud-config
          hostname: webserver
          fqdn: webserver.example.com
          manage_etc_hosts: true
          users:
            - name: ansible
              groups: sudo
              shell: /bin/bash
              sudo: ['ALL=(ALL) NOPASSWD:ALL']
              ssh_authorized_keys:
                - {{ lookup('file', '~/.ssh/id_rsa.pub') }}
          package_upgrade: true
          packages:
            - qemu-guest-agent
      delegate_to: localhost

    - name: Create cloud-init user data for dbserver
      copy:
        dest: /var/lib/libvirt/images/dbserver-user-data
        content: |
          #cloud-config
          hostname: dbserver
          fqdn: dbserver.example.com
          manage_etc_hosts: true
          users:
            - name: ansible
              groups: sudo
              shell: /bin/bash
              sudo: ['ALL=(ALL) NOPASSWD:ALL']
              ssh_authorized_keys:
                - {{ lookup('file', '~/.ssh/id_rsa.pub') }}
          package_upgrade: true
          packages:
            - qemu-guest-agent
      delegate_to: localhost

    - name: Create cloud-init ISO for webserver
      command: >
        genisoimage -output /var/lib/libvirt/images/webserver-cidata.iso
        -volid cidata -joliet -rock /var/lib/libvirt/images/webserver-user-data
      args:
        creates: /var/lib/libvirt/images/webserver-cidata.iso

    - name: Create cloud-init ISO for dbserver
      command: >
        genisoimage -output /var/lib/libvirt/images/dbserver-cidata.iso
        -volid cidata -joliet -rock /var/lib/libvirt/images/dbserver-user-data
      args:
        creates: /var/lib/libvirt/images/dbserver-cidata.iso

    - name: Define and start webserver VM
      virt:
        name: webserver
        memory: 2048
        vcpus: 2
        disks:
          - device: disk
            path: /var/lib/libvirt/images/webserver.qcow2
          - device: cdrom
            path: /var/lib/libvirt/images/webserver-cidata.iso
        networks:
          - network: default
        boot: hd
        graphics: none
        state: running

    - name: Define and start dbserver VM
      virt:
        name: dbserver
        memory: 2048
        vcpus: 2
        disks:
          - device: disk
            path: /var/lib/libvirt/images/dbserver.qcow2
          - device: cdrom
            path: /var/lib/libvirt/images/dbserver-cidata.iso
        networks:
          - network: default
        boot: hd
        graphics: none
        state: running
